version: '3.8'

services:
  backend:
    build:
      context: ./Back/Ecommerce
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    networks:
      - ecommerce-network

  frontend:
    build:
      context: ./eccomercefront
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    restart: always
    ports:
      - "3000:80"
    env_file:
      - .env
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
